# Generated by Django 2.2.17 on 2021-06-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='follwers',
            new_name='followers',
        ),
    ]
