# Generated by Django 2.2.17 on 2021-06-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0002_auto_20210607_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
