# Generated by Django 2.2.17 on 2021-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0009_post_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
