# Generated by Django 2.2.17 on 2021-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0019_message_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='connection',
            field=models.CharField(blank=True, default='hii', max_length=200, null=True),
        ),
    ]
