# Generated by Django 2.2.17 on 2021-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0022_remove_detail_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='connection',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, null=True)),
                ('message', models.ManyToManyField(blank=True, related_name='messages', to='src_code.Message')),
            ],
        ),
    ]
