# Generated by Django 2.2.17 on 2021-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0028_auto_20210615_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://images.unsplash.com/photo-1523734650021-75837a627245?ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw1fHx8ZW58MHx8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60', null=True, upload_to='media/% Y/% m/% d/'),
        ),
    ]
