# Generated by Django 2.2.17 on 2021-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0029_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='Recoverd_jpg_file10-1-300x165.jpg', null=True, upload_to='media/% Y/% m/% d/'),
        ),
    ]
