# Generated by Django 2.2.17 on 2021-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0030_auto_20210621_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/% Y/% m/% d/'),
        ),
    ]
