# Generated by Django 2.2.17 on 2021-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0031_auto_20210621_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', null=True, upload_to='media/% Y/% m/% d/'),
        ),
    ]
