# Generated by Django 2.2.17 on 2023-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0033_auto_20210626_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='bool_abuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='bool_hate',
            field=models.BooleanField(default=False),
        ),
    ]
